name: Deploy Frontend to S3

on:
  pull_request:
    branches:
      - main # main 브랜치로 PR이 병합될 때 실행
    paths:
      - "front/**" # front 폴더 내 파일들이 변경될 때만 실행

jobs:
  deploy:
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'fe/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 레포지토리 코드 체크아웃

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm" # pnpm 캐시 설정

      - name: Install pnpm
        run: |
          npm install -g pnpm # pnpm 설치
          echo $PATH # PATH 환경 변수 출력

      - name: Install dependencies
        run: pnpm install # 의존성 설치

      - name: Build project
        run: pnpm run build --prefix front # front 폴더에서 빌드 실행

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pnpm install aws-cli -g
          aws s3 sync ./front/dist s3://honeydevelop.com --delete --region ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
